// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unobpebkuukbydjmvjsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVub2JwZWJrdXVrYnlkam12anN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mzc1ODcsImV4cCI6MjA2NjUxMzU4N30.qRdEcN-YJ_QllU4JLeIFmk_bzUPsoM7KFUj1S2wEUg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);